version: "3.3"
services:

    #######################################################
    #  Rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - booking


    #######################################################
    #  Postgress
    #######################################################
  postgres:
   container_name: postgres
   image: postgres:latest
   restart: unless-stopped
   ports:
    - '5432:5432'
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   networks:
    - booking

networks:
  booking: